### ISSUE TITLE
Status attributes should not be on the class

### ISSUE THREAD

**Issue by ghislainbourgeois** [PietroPasotti/compound-status#26]
In the documentation, it is suggested to do something like this:

```
class MyPool(StatusPool):
    """This defines my charm's status pool."""
    workload = Status()  # this tracks the workload status
    relation_1 = Status()  # this tracks my integration #1
    relation_2 = Status()  # this tracks my integration #2
```

This works fine when used in a production charm because the class lives only for the duration of an event. However, when running unit tests, the class is loaded only once for all tests. This breaks independence between tests:

```
class TestCharm(unittest.TestCase):
    def setUp(self):          
          self.namespace = "whatever"
          self.harness = testing.Harness(MagmaOrc8rOrchestratorCharm)
          self.harness.set_model_name(name=self.namespace)
          self.harness.begin()

    def test_can_set_active_status(self):
          """This test will pass."""
          self.harness.charm.status_pool.workload = ActiveStatus()
          self.harness.charm.commit()
          self.assertEqual(self.harness.charm.status_pool.workload.name, "active")

    def test_status_should_be_unknown_on_start(self):
          """This test will fail when run with the suite, and pass when run individually."""
          self.assertEqual(self.harness.charm.status_pool.workload.name, "unknown")
```

Making the statuses instance variables also does not work according to my testing, because somehow the call to `super().__init__()` gets to `ops.framework` under test. I did not get a chance to investigate further.

**Comment by PietroPasotti** [comment]
So this is a similar situation tot he known shortcoming of the Harness, that the charm is not properly reinitialized on each test.
The solution here would be to make the status class definition and the charm class definition part of the setUp routine.
Not sure I see a cleaner solution here.
